server:
  port: 8080

spring:
  # jdbc? ?? DB ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/member
    username: root
    password: 1234
  # jpa ??
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

# mybatis ??
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml